name: Build and push docker image

on:
  push:
    tags:
      - '[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get docker image version
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/http-dump:${{ steps.get_version.outputs.version }}
